### ISSUE TITLE
Error when reindexing after upgrade to 0.8.2

### ISSUE THREAD

**Issue by mskog** [ankane/searchkick#282]
I upgraded Searchkick from 0.7.1 to 0.8.2 and when I tried to reindex I got this error:
`NoMethodError: undefined method `searchkick_klass' for nil:NilClass
from /var/www/dodofeed/shared/bundle/ruby/2.1.0/gems/searchkick-0.8.2/lib/searchkick/logging.rb:42:in `import_with_instrumentation'`

I've tried to remove the index and redo it but it didn't help. Downgrading to 0.7.1 "fixed" the problem.
I am using Elasticsearch 1.3.2
