### ISSUE TITLE
NoMethodError (undefined method 'options' for an instance of Searchkick::Relation)

### ISSUE THREAD

**Issue by paulwalk** [ankane/searchkick#1727]
**Describe the bug**
`NoMethodError (undefined method 'options' for an instance of Searchkick::Relation)`

**To reproduce**
After upgrading from v5.5.2 to v6.0.0 I get the error:
`NoMethodError (undefined method 'options' for an instance of Searchkick::Relation)`

I'm not able to supply the calling code - my code does not explicitly call this missing method. I am using searchkick with `pagy (9.4.0)` and it seems that the `Pagy.new_from_searchkick()` method is the one calling the missing `results` method/attribute:

```ruby
@systems = System.search(
      search_terms,
      fields: [:name, :short_name, :aliases, :owner_names],
      where: conditions,
      order: { name: :asc },
      aggs: facets,
      page: page,
      per_page: per_page,
      includes: [:network_checks, :repoids, :users, :metadata_formats],
      misspellings: false
    )

[...]

@pagy = Pagy.new_from_searchkick(@systems)
```

**Additional context**
I have also tried v6.0.1 & v6.0.2.

Looking at the diff between v5.5.2 and v6.0.0 I guess this may be caused by the [removal of the `options` attribute in this commit?](https://github.com/ankane/searchkick/commit/0d01ea0dcf00da3ff0cdaeb6f28df7fdc5f1b00a)
